### ISSUE TITLE
[bug] Helm install times out with no details

### ISSUE THREAD

**Issue by blaisep** [PostHog/charts#7] opened 2020-06-15 22:29 UTC
I haven't run into this problem before:
```
helm install posthog posthog/posthog --debug --timeout 5m0s
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /Users/bpabon/Library/Caches/helm/repository/posthog-1.3.0.tgz

client.go:108: [debug] creating 18 resource(s)
client.go:258: [debug] Starting delete for "posthog-migrate" Job
client.go:108: [debug] creating 1 resource(s)
client.go:467: [debug] Watching for changes to Job posthog-migrate with timeout of 5m0s
client.go:495: [debug] Add/Modify event for posthog-migrate: ADDED
client.go:534: [debug] posthog-migrate: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Error: failed post-install: timed out waiting for the condition
helm.go:84: [debug] failed post-install: timed out waiting for the condition
```

Kubectl
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:50:54Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
Helm
```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**Comment by blaisep** [comment] 2020-06-16 04:27
This duplicates
 https://github.com/PostHog/posthog/issues/1025

**Comment by fuziontech** [comment] 2020-06-16 04:49
Thanks for moving this over here, it definitely makes more sense.

I just spun up a fresh k8s cluster on DigitalOcean to test this and it seemed to work. My versions of helm and kubectl 

Can you try running:
```
helm repo update
```
and then try installing the chart?

my versions are even lined up with yours
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
and 
```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```
Your go version locally is `14.x` where mine is `13.x` I will upgrade that and see if anything changes

**Comment by fuziontech** [comment] 2020-06-16 04:53
seems like that is the version of go kubectl was compiled with. I am also on ubuntu right now, will try on a mac to see if there is any difference

**Comment by blaisep-vgs** [comment] 2020-06-17 20:36
Hi @fuziontech , 
FWIW, I get the same result on a different Mac (10.5.5)
where the `helm version`
is only slightly different:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```
without changing an versions on my

**Comment by fuziontech** [comment] 2020-06-18 01:19
Where is the cluster hosted? Bare metal or managed?

**Comment by blaisep** [comment] 2020-06-18 04:50
Digital ocean kubernetes service 1.17
It's possible there maybe on OOM issue, this time I noticed that several
pods came up, but not the postgresql pod
FWIW, I will go to the hosted version because I really want to make
progress on this.

**Comment by fuziontech** [comment] 2020-06-18 06:10
strange... I tried this on hosted k8s on DO to try to replicate it before and it booted right up. I'll keep an eye on this and if you can think of any other possibilities let me know.

**Comment by blaisep-vgs** [comment] 2020-06-18 06:57
ok... I wonder if this is a osx 10.15 thing because I get the same behavior
when I target k3d on my laptop...

**Comment by fuziontech** [comment] 2020-06-18 18:16
sounds like a lead to me! going to try now on a laptop with 10.15.5

**Comment by fuziontech** [comment] 2020-06-18 18:48
With the smallest cluster possible on DO and on a mac with 10.15.5 I can reproduce this now 👀

**Comment by blaisep-vgs** [comment] 2020-06-18 18:58
Thanks so much for trying! Your tenacity is inspiring.
Wouldn't it be nice if helm gave a little more feedback?

**Comment by fuziontech** [comment] 2020-06-18 21:29
I think it might just be due to cluster size. It's hanging for me now on ubuntu as well on the small cluster. Can you try bumping the size? You are probably right. Pod blowing out memory .

If you up the size of the nodes it seems to work. I'm using the minimum 'production' size that DO provides with 3 nodes so about $60 a month in cost.
`4 GB Memory / 80 GB Disk + 8 GB / SFO3`

**Comment by blaisep-vgs** [comment] 2020-06-18 22:05
Hi James,

In this particular case, I prefer not to increase the cost of my personal
cluster. If our ops guys want to set this up on AWS, then size will not
matter (for a change).
I suppose you can use these findings to warn about system requirements in
the README.

Cheers,
Blaise

**Comment by fuziontech** [comment] 2020-06-19 21:36
These two PRs should address this and I'll also think about ways we can reduce the required memory size on this
https://github.com/PostHog/posthog.com/pull/148
https://github.com/PostHog/charts/pull/9

**Closed by fuziontech** 2020-06-19 21:36 UTC
